replicaCount: 1

image:
  repository: ghcr.io/milo-akb/network-exporter
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

containerPort: 8000

env:
  PING_INTERVAL: 10
  EXPORTER_PORT: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

securityContext:
  capabilities:
    add:
      - NET_RAW

config:
  targets:
    - address: 8.8.8.8
      ping_count: 5
      timeout: 1.0
      packet_size: 64
      protocol: icmp
      labels:
        name: google_dns
        location: global
    - address: 1.1.1.1
      ping_count: 5
      timeout: 1.0
      packet_size: 64
      protocol: icmp
      labels:
        name: cloudflare_dns
        location: global
    - address: 208.67.222.222
      ping_count: 5
      timeout: 1.0
      packet_size: 64
      protocol: icmp
      labels:
        name: opendns
        location: global
    - address: example.com
      protocol: http
      port: 80
      timeout: 5.0
      labels:
        name: example_http
        location: global
    - address: google.com
      protocol: https
      port: 443
      timeout: 5.0
      labels:
        name: google_https
        location: global
    - address: cloudflare.com
      protocol: dns
      dns_server: 1.1.1.1
      dns_port: 53
      timeout: 5.0
      labels:
        name: cloudflare_dns_resolve
        location: global
    - address: example.com
      protocol: tcp
      port: 80
      timeout: 5.0
      labels:
        name: example_tcp
        location: global
    - address: 8.8.8.8
      protocol: udp
      port: 53
      timeout: 5.0
      labels:
        name: google_dns_udp
        location: global
    - address: pool.ntp.org
      protocol: ntp
      timeout: 5.0
      ntp_version: 3
      labels:
        name: ntp_pool
        location: global
